import { saleInvoiceList } from "./saleofferlist";

export const invoceLists: saleInvoiceList[] = [
  {
    id: 101,
    project_name: 'Pineapple Inc.',
    selling_price: '34y38434',
    bedrooms :  '43',
    total_area : '32sqft',
    built_up_area : '16sqft',
    payable_now   : '237232',
    orders: [
      {
        itemName: 'Courge',
        unitPrice: 10,
        // units: 9,
        // unitTotalPrice: 90,
      },
    ],
    orderDate: new Date(),
    totalCost: 90,
    vat: 9,
    grandTotal: 99,
    status: 'Shipped',
    completed: false,
    isSelected: false,
  },
  {
    id: 102,
    project_name: 'Pineapple.',
    selling_price: '34y38434',
    bedrooms :  '4',
    total_area : '32sqft',
    built_up_area : '16sqft',
    payable_now   : '237232',
    orders: [
      {
        itemName: 'Courge',
        unitPrice: 10,
        // units: 9,
        // unitTotalPrice: 90,
      },
    ],
    orderDate: new Date(),
    totalCost: 90,
    vat: 9,
    grandTotal: 99,
    status: 'Delivered',
    completed: false,
    isSelected: false,
  },
  {
    id: 103,
    project_name: 'Incorporation.',
    selling_price: '34y38434',
    bedrooms : '4',
    total_area : '32sqft',
    built_up_area : '16sqft',
    payable_now   : '237232',
    orders: [
      {
        itemName: 'Courge',
        unitPrice: 10,
        // units: 9,
        // unitTotalPrice: 90,
      },
    ],
    orderDate: new Date(),
    totalCost: 90,
    vat: 9,
    grandTotal: 99,
    status: 'Pending',
    completed: false,
    isSelected: false,
  },
  {
    id: 104,
    project_name: 'PineappleTimes  .',
    selling_price: '34y38434',
    bedrooms : '4',
    total_area : '32sqft',
    built_up_area : '16sqft',
    payable_now   : '237232',
    orders: [
      {
        itemName: 'Courge',
        unitPrice: 10,
        // units: 9,
        // unitTotalPrice: 90,
      },
    ],
    orderDate: new Date(),
    totalCost: 90,
    vat: 9,
    grandTotal: 99,
    status: 'Shipped',
    completed: false,
    isSelected: false,
  }
];
